NDEF_URIPREFIX_NONE = 0x00
NDEF_URIPREFIX_HTTP_WWWDOT = 0x01
NDEF_URIPREFIX_HTTPS_WWWDOT = 0x02
NDEF_URIPREFIX_HTTP = 0x03
NDEF_URIPREFIX_HTTPS = 0x04
NDEF_URIPREFIX_TEL = 0x05
NDEF_URIPREFIX_MAILTO = 0x06
NDEF_URIPREFIX_FTP_ANONAT = 0x07
NDEF_URIPREFIX_FTP_FTPDOT = 0x08
NDEF_URIPREFIX_FTPS = 0x09
NDEF_URIPREFIX_SFTP = 0x0A
NDEF_URIPREFIX_SMB = 0x0B
NDEF_URIPREFIX_NFS = 0x0C
NDEF_URIPREFIX_FTP = 0x0D
NDEF_URIPREFIX_DAV = 0x0E
NDEF_URIPREFIX_NEWS = 0x0F
NDEF_URIPREFIX_TELNET = 0x10
NDEF_URIPREFIX_IMAP = 0x11
NDEF_URIPREFIX_RTSP = 0x12
NDEF_URIPREFIX_URN = 0x13
NDEF_URIPREFIX_POP = 0x14
NDEF_URIPREFIX_SIP = 0x15
NDEF_URIPREFIX_SIPS = 0x16
NDEF_URIPREFIX_TFTP = 0x17
NDEF_URIPREFIX_BTSPP = 0x18
NDEF_URIPREFIX_BTL2CAP = 0x19
NDEF_URIPREFIX_BTGOEP = 0x1A
NDEF_URIPREFIX_TCPOBEX = 0x1B
NDEF_URIPREFIX_IRDAOBEX = 0x1C
NDEF_URIPREFIX_FILE = 0x1D
NDEF_URIPREFIX_URN_EPC_ID = 0x1E
NDEF_URIPREFIX_URN_EPC_TAG = 0x1F
NDEF_URIPREFIX_URN_EPC_PAT = 0x20
NDEF_URIPREFIX_URN_EPC_RAW = 0x21
NDEF_URIPREFIX_URN_EPC = 0x22
NDEF_URIPREFIX_URN_NFC = 0x23

URI_PREFIX_MAP = {
    '' : NDEF_URIPREFIX_NONE,
    "http://www.": NDEF_URIPREFIX_HTTP_WWWDOT,
    "https://www.": NDEF_URIPREFIX_HTTPS_WWWDOT,
    "http:": NDEF_URIPREFIX_HTTP,
    "https:": NDEF_URIPREFIX_HTTPS,
    "tel:": NDEF_URIPREFIX_TEL,
    "mailto:": NDEF_URIPREFIX_MAILTO,
    "ftp://anonymous:anonymous@": NDEF_URIPREFIX_FTP_ANONAT,
    "ftp://ftp.": NDEF_URIPREFIX_FTP_FTPDOT,
    "ftps:": NDEF_URIPREFIX_FTPS,
    "sftp:": NDEF_URIPREFIX_SFTP,
    "smb:": NDEF_URIPREFIX_SMB,
    "nfs:": NDEF_URIPREFIX_NFS,
    "ftp:": NDEF_URIPREFIX_FTP,
    "dav:": NDEF_URIPREFIX_DAV,
    "news:": NDEF_URIPREFIX_NEWS,
    "telnet:": NDEF_URIPREFIX_TELNET,
    "imap:": NDEF_URIPREFIX_IMAP,
    "rtsp:": NDEF_URIPREFIX_RTSP,
    "urn:": NDEF_URIPREFIX_URN,
    "pop:": NDEF_URIPREFIX_POP,
    "sip:": NDEF_URIPREFIX_SIP,
    "sips:": NDEF_URIPREFIX_SIPS,
    "tftp:": NDEF_URIPREFIX_TFTP,
    "btspp://": NDEF_URIPREFIX_BTSPP,
    "btl2cap://": NDEF_URIPREFIX_BTL2CAP,
    "btgoep://": NDEF_URIPREFIX_BTGOEP,
    "tcpobex://": NDEF_URIPREFIX_TCPOBEX,
    "irdaobex://": NDEF_URIPREFIX_IRDAOBEX,
    "file://": NDEF_URIPREFIX_FILE,
    "urn:epc:id:": NDEF_URIPREFIX_URN_EPC_ID,
    "urn:epc:tag:": NDEF_URIPREFIX_URN_EPC_TAG,
    "urn:epc:pat:": NDEF_URIPREFIX_URN_EPC_PAT,
    "urn:epc:raw:": NDEF_URIPREFIX_URN_EPC_RAW,
    "urn:epc:": NDEF_URIPREFIX_URN_EPC,
    "urn:nfc:": NDEF_URIPREFIX_URN_NFC,
}

TNF_EMPTY = 0x00
TNF_WELL_KNOWN = 0x01
TNF_MIME_MEDIA = 0x02
TNF_ABSOLUTE_URI = 0x03
TNF_EXTERNAL_TYPE = 0x04
TNF_UNKNOWN = 0x05
TNF_UNCHANGED = 0x06
TNF_RESERVED = 0x07

RECORD_TYPE_TEXT = 'T'
RECORD_TYPE_URI = 'U'
RECORD_TYPE_MIME = 'M'
RECORD_TYPE_SMART_POSTER = 'Sp'
RECORD_TYPE_ALTERNATIVE_CARRIER = 'ac'
RECORD_TYPE_HANDOVER_CARRIER = 'Hc'
RECORD_TYPE_HANDOVER_REQUEST = 'Hr'
RECORD_TYPE_HANDOVER_SELECT = 'Hs'
